In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("sales_dirty.csv")

In [2]:
df.head()

   OrderID   OrderDate        Product Quantity UnitPrice       City
0     5001  2026-04-01         Laptop      2.0     650.0    Chennai
1     5002  2026-04-02          Mouse      5.0      18.5  Bengaluru
2     5003  2026-04-03        Monitor      2.0     180.0  Hyderabad
3     5004  2026-04-04       Keyboard      3.0      32.0     Mumbai
4     5005  2026-04-05  Gaming Laptop      1.0    1450.0       Pune

In [3]:
df.shape

(65, 6)

In [4]:
df.columns

Index(['OrderID', 'OrderDate', 'Product', 'Quantity', 'UnitPrice', 'City'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    65 non-null     int64
 1   OrderDate  64 non-null     str
 2   Product    64 non-null     str
 3   Quantity   64 non-null     str
 4   UnitPrice  64 non-null     str
 5   City       64 non-null     str
dtypes: int64(1), str(5)
memory usage: 3.2 KB

In [6]:
df.describe(include="all")

            OrderID   OrderDate Product Quantity UnitPrice     City
count     65.000000          64      64       64        64       64
unique          NaN          28      13        9        15       60
top             NaN  2026-04-01  Laptop      1.0     650.0  Chennai
freq            NaN           3       6       19         6        2
mean    5030.169231         NaN     NaN      NaN       NaN      NaN
std       18.841086         NaN     NaN      NaN       NaN      NaN
min     5001.000000         NaN     NaN      NaN       NaN      NaN
25%     5014.000000         NaN     NaN      NaN       NaN      NaN
50%     5030.000000         NaN     NaN      NaN       NaN      NaN
75%     5046.000000         NaN     NaN      NaN       NaN      NaN
max     5064.000000         NaN     NaN      NaN       NaN      NaN

In [7]:
df.isnull().sum()

OrderID      0
OrderDate    1
Product      1
Quantity     1
UnitPrice    1
City         1
dtype: int64

In [8]:
df["UnitPrice"] = pd.to_numeric(
    df["UnitPrice"], errors="coerce"
)

In [9]:
df["UnitPrice"]

0        650.00
1         18.50
2        180.00
3         32.00
4       1450.00
        ...
60       650.00
61       180.00
62        18.50
63    999999.00
64        89.99
Name: UnitPrice, Length: 65, dtype: float64

In [10]:
df["UnitPrice"].max()

np.float64(999999.0)

In [11]:
df.loc[
    df["UnitPrice"].idxmax(),
    ["Product", "UnitPrice"]
]

Product      Keyboard
UnitPrice    999999.0
Name: 63, dtype: object

In [12]:
df[df["UnitPrice"] == df["UnitPrice"].max()][
    ["OrderID", "Product", "UnitPrice", "City"]
]

    OrderID   Product  UnitPrice       City
63     5064  Keyboard   999999.0  Bengaluru